### ISSUE TITLE
Support for Coffe-Script 1.9

### ISSUE THREAD

**Issue by amitevski** [Clever/coffee-jshint#17]
currently only coffee 1.8 is supported.

**Comment by danielbprice** [comment]
+1, this would really help my project.

**Comment by rodw** [comment]
For what it is worth I've published a fork of coffee-jshint that is configured to work with CoffeeScript 1.9.x on npm as [`coffee-19-jshint`](https://www.npmjs.com/package/coffee-19-jshint), with a GitHub repository at [rodw/coffee-jshint](https://github.com/rodw/coffee-jshint).

To install it:

    npm install coffee-19-jshint -g

etc.

Otherwise it should work exactly the same as the original coffee-jshint.

I'd be more than happy to remove my fork, or at least abandon it, once Clever/coffee-jshint is updated to allow CoffeeScript 1.9.

**Comment by jonahkagan** [comment]
@amitevski or @rodw would either of you be willing to submit a pull request with the relevant changes?

**Comment by jonahkagan** [comment]
Ah wait, just saw that you already did. My bad

**Comment by cueedee** [comment]
May I ask wether there are compelling reasons to keep the `coffee-script` peer-depency so restrictive? The [npm documentation](https://docs.npmjs.com/files/package.json#peerdependencies) appears to encourage a more permissive style when it comes to specifying `peerDependencies`:

>Trying to install another plugin with a conflicting requirement will cause an error. For this reason, make sure your plugin requirement is as broad as possible, and not to lock it down to specific patch versions.
>
> Assuming the host complies with semver, only changes in the host package's major version will break your plugin. Thus, if you've worked with every 1.x version of the host package, use "^1.0" or "1.x" to express this. If you depend on features introduced in 1.5.2, use ">= 1.5.2 < 2".

From this I would gather that `"coffee-script": ">= 1.6 < 2"` would make a lot more sense.
